defmodule Gogls.Media.Game do
    defstruct developer: "",
    title: "",
    category: "",
    available: nil,
    originalCategory: "",
    image: "",
    slug: "",
    rating: "",
    id: 0,
    genres: [],
    price: 0,
    is_coming_soon: nil,
    is_price_visible: nil,
    extra_info: [],
    supported_operating_systems: [],
    is_in_development: nil,
    is_tba: nil,
    age_requirement: 0,
    release_date: nil,
    support_url: "",
    forum_url: "",
    global_release_date: nil,
    custom_attributes: [],
    video: nil,
    gallery: [],
    publisher: "",
    is_discounted: nil,
    is_wishlistable: nil
end